language: minimal

jobs:
  include:
    - name: macOS 10.10
      os: osx
      osx_image: xcode6.4
    - name: macOS 10.11
      os: osx
      osx_image: xcode8.0
    - name: macOS 10.12      
      os: osx
      osx_image: xcode9.2
    - name: macOS 10.13
      os: osx
      osx_image: xcode10.1
    - name: macOS 10.14
      os: osx
      osx_image: xcode11.3

script:
  - wget -q https://github.com/canonical/multipass/releases/download/v1.0.0/multipass-1.0.0+mac-Darwin.pkg
  - tar xzfO multipass-1.0.0+mac-Darwin.pkg --include '*multipass.pkg/Payload' | gzip -dc | (cd /; sudo cpio -id)
  - sw_vers
  - otool -L /Library/Application\ Support/com.canonical.multipass/bin/multipass
  - /Library/Application\ Support/com.canonical.multipass/bin/multipass version
